### ISSUE TITLE
那个招聘的webapp

### ISSUE THREAD

**Issue by aaamoon** [capslocktao/private-project#1]
你好，我想问一下，我下载到本地试了一下招聘那个webapp项目，页面怎么隔几秒就刷新一次，不会停的，怎么解决呢？

**Comment by neroneroffy** [comment]
这个项目不是纯前端的项目，要在react_recruiment_webapp目录下的server启动node.js服务器，还要有mongodb做数据库，不知道你数据库和node.js服务器正常不。我刚才打开了这项目，没开服务器的话，是一直有加载中的弹框的。但是不刷新页面。你看下有没有报错信息。可以的话，再详细描述下问题

**Comment by aaamoon** [comment]
嗯嗯对的node和数据库和那些都弄好了，一切正常，和你的动图一样，就是全部页面都会每隔三秒刷新一次，手速慢点打字时都登录不上。
下面是server命令行启动数据库后，也没有地方报错呀，就是页面一直刷新，然后命令行就是一直更新下面的内容，哈哈
GET /users/getmsglist 200 8.423 ms - 1114
GET /users/info 200 5.077 ms - 143
GET /users/getmsglist 200 10.805 ms - 1114
GET /users/info 200 4.892 ms - 143
GET /users/getmsglist 200 21.781 ms - 1114
GET /users/info 200 5.892 ms - 143
GET /users/getmsglist 200 12.872 ms - 1114
GET /users/info 200 4.690 ms - 143
GET /users/getmsglist 200 16.368 ms - 1114
GET /users/info 200 7.934 ms - 143
GET /users/getmsglist 200 9.295 ms - 1114
GET /users/info 200 6.742 ms - 143
GET /users/getmsglist 200 7.777 ms - 1114
GET /users/info 200 4.615 ms - 143
GET /users/getmsglist 200 9.914 ms - 1114
GET /users/info 200 4.754 ms - 143
GET /users/getmsglist 200 10.919 ms - 1114
GET /users/info 200 9.297 ms - 143
GET /users/getmsglist 200 9.235 ms - 1114
GET /users/info 200 9.859 ms - 143
GET /users/getmsglist 200 12.137 ms - 1114
GET /users/info 200 4.193 ms - 143
GET /users/getmsglist 200 10.817 ms - 1114

**Comment by neroneroffy** [comment]
我刚刚在公司电脑上跑了一下这项目，确实没遇到你这问题，没有刷新。。这应该是一直在获取用户信息

**Comment by aaamoon** [comment]
哦哦这样子啊，那应该是我自己的问题。我想问一下这种有mongodb的项目除了在本地localhost预览外，怎么才可以实现在网站上预览呢，用github-pages可以吗？

**Comment by neroneroffy** [comment]
放在github-pages上是预览不了的，因为有后台程序，数据都是由后台动态提供的，要自己有个服务器，在服务器上配置mongodb，然后部署代码，就可以了

**Comment by aaamoon** [comment]
哦哦这样子，明白啦，谢谢你！

**Comment by aaamoon** [comment]
老大我刚刚试了下那个vue上传图片的那个项目，上传图片时失败了，报错“上传失败123”
下面是服务器命令行的报错信息：
已经链接数据库
GET /menudatas 200 78.365 ms - 262
8053cdb0-1ac7-11e8-9753-2764652bb25e
GET /query?mark=8053cdb0-1ac7-11e8-9753-2764652bb25e 200 18.062 ms - 37
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'F:\project\vue\vue_uploader\my-s
erver\public\images\upload_6ff47008068ae2e2b50894158d5aa554.png'

**Comment by neroneroffy** [comment]
这个问题是后台接受图片，进行重命名的时候，报的错误。
F:\project\vue\vue_uploader\my-server\public\images\  这是我写的时候，我本机的图片存放路径，你应该需要改成你自己的路径。
在项目的private-project/vue_uploader/my-server/routes/upload.js这个文件里的34行，改成你自己的路径试试

**Comment by aaamoon** [comment]
我按照你说的改了一下，现在可以了，谢谢大神哈哈！

**Comment by neroneroffy** [comment]
么事么事，哈哈
