### ISSUE TITLE
node的初学者,想请问一下怎么把vue_shop中的json数据导入到mogonDB

### ISSUE THREAD

**Issue by est7** [capslocktao/private-project#2]
启动了mongoDB,也新建了vueshop表,但是不知道怎么把转到数据库里

**Comment by est7** [comment]
在访问时报如下错误
``` 
MongoDB connected disconnected
MongoDB connected fail
```

不太清楚是哪里少操作了,新手不太懂后台配置

**Comment by neroneroffy** [comment]
我是下载了个studio 3T,这是mongoDB的可视化管理工具，你装一个它，然后用它连接你那个应用的数据库，然后就可以在数据库里新建集合以及在集合中导入json文件了。你这报错是数据库链接失败了，好好查下哪里有没有问题。不太清楚你那的mongo怎么配置的

**Comment by est7** [comment]
@capslocktao 您好,在代码中
```
mongoose.connect('mongodb://127.0.0.1:27017/vueshop');
```
我看到了数据库名为vueshop,两个文档要放在集合里,集合的名称我是自己随便起吗?

**Comment by est7** [comment]
在MongoDB中，如果向一个不存在的集合中插入文档，则对应的数据库（默认为test）会创建一个集合，Mongoose同样遵循这个原则，并且在新创建的数据库的命名上面也颇有讲究

判断模型名(Model)是否可数，如果不可数直接返回模型名作为新集合的名称；如果可数，则返回模型名的复数形式作为新集合的名称（模型名+'s')

**Comment by est7** [comment]
看来还是要多看文档谢谢了

**Comment by neroneroffy** [comment]
哈哈。我上班来的没看到，确实要多看文档，我的mongoDB也正在踩坑
