### ISSUE TITLE
图片上传

### ISSUE THREAD

**Issue by baobaos** [capslocktao/private-project#3]
大神，我的vue下报错
Your application is running here: http://localhost:8082
[HPM] Error occurred while trying to proxy request /favicon.ico from localhost:8082 to http://localhost:3002 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)
[HPM] Error occurred while trying to proxy request /menudatas from localhost:8082 to http://localhost:3002 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)
[HPM] Error occurred while trying to proxy request /upload?mark=new from localhost:8082 to http://localhost:3002 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)

这是怎磨回事啊

**Comment by neroneroffy** [comment]
看样子是跑的前端服务跨域代理到后台服务时出错了，项目里的my-server那个node后台服务你启动了吗？这个要运行俩服务，前端的webpack-dev-server，就是vue的前端服务，和express的node服务，来接收图片用

**Comment by baobaos** [comment]
[nodemon] 1.18.3
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node app.js`
已经链接数据库

后台显示已经连接

**Comment by baobaos** [comment]
不知道哪里出错了，

**Comment by neroneroffy** [comment]
我是在这文件里设置的跨域：vue_uploader/vue-upload-font-end/config/index.js。看样子可能是跨域代理设置的问题，你看下这个文章里有相同的报错信息https://www.jb51.net/article/142086.htm。另外你可以直接在package.json里设置跨域，看行不行

**Comment by baobaos** [comment]
proxyTable: {
            '*': {
                target: "http://localhost:3002",         这里的后台地址不能访问，是什么问题啊？
                changeOrigin: true,
                pathRewrite: {

                }
            }


        },

**Comment by neroneroffy** [comment]
这后台地址是node服务器的地址，你说的不能访问是什么，意思？

**Comment by baobaos** [comment]
![kni 8rwi q jj_t clpb x](https://user-images.githubusercontent.com/36978837/44570960-0d107600-a7b2-11e8-8f51-8ab0d1456f50.png)

就是点开它，显示的是无法访问此网站

**Comment by neroneroffy** [comment]
应该就是后台服务可能没运行起来。我周末把环境整好，检查一下再回复你。这还是在原来的电脑上写的项目

**Comment by baobaos** [comment]
好的，谢谢

**Comment by neroneroffy** [comment]
我这里项目跑起来后一切正常的。你的问题应该是后台没启动成功，如果启动成功，访问localhost:3002,会返回express页面的。你nodemon启动的方式不对，不是node app.js，它不是启动文件，而是node ./bin/www ，或者在my-server下npm start也可以。启动后将文件上传目录改成自己的本地目录后上传还会遇到个问题：Unknown modifier: $pushAll ，应该是版本问题导致的， 具体解决办法在这里：https://segmentfault.com/q/1010000012568462
![image](https://user-images.githubusercontent.com/29172371/44616841-5b914380-a88a-11e8-89db-e7954dba67d1.png)
